# breadcrumb.yml
# Configuration of the main breadcrumb (BreadcrumbConfig service)
#
# Define a recursive tree of the site pages which show the breadcrumb.
# For every page, set attributes label an route (route name).
# If the route needs mandatory parameters, add a defaults attributes, with the defaults parameters.
# To define subpages, add a pages attribute.
#
# Example:
#
# home:
#   label: Home
#   route: homepage
#   pages:
#     page1:
#       label: Page 1
#       route: page_1
#       defaults:
#         id: 1
#         name: x

# The breadcrumb for the configurator part of the application is too complex to be calculated here,
# so the calculated breadcrumb is replaced in base template, by the one in the breadcrumb block
# in the configurator templates

home:
  label: Breadcrumb.Home
  route: homepage
  pages:
    integration:
      label: Breadcrumb.Integration
      route: jdd_list
      pages:
        newjdd:
          label: Breadcrumb.Integration.New
          route: jdd_new
        newintegration:
          label: Breadcrumb.Integration.New
          route: integration_creation
        integrationupload:
          label: Breadcrumb.Integration.New
          route: integration_upload_data
          defaults:
            id: 1
    jdd:
      label: Breadcrumb.Integration
      route: jdd_list
      pages:
        showDetail:
          label: Breadcrumb.Integration.Show
          route: jdd_show 
          defaults:
            id: 1
    checkconf:
      label: Breadcrumb.Check.Configuration
      route: checkconf_showconfig
    user:
      label: Breadcrumb.User
      route: user_home
    usermanagement:
      label: Breadcrumb.Users.Administration
      route: usermanagement_home
      pages:
        users:
          label: Breadcrumb.Users
          route: usermanagement_showUsers
          pages:
            edituser:
              label: Breadcrumb.Edit.User
              route: usermanagement_editUser
            passworduser:
              label: Breadcrumb.Change.Password
              route: usermanagement_changePassword
              defaults:
                login: xxx
        roles:
          label: Breadcrumb.Roles
          route: usermanagement_showRoles
          pages:
            editrole:
              label: Breadcrumb.Edit.Role
              route: usermanagement_editRole
        providers:
          label: Breadcrumb.Providers
          route: usermanagement_showProviders
          pages:
            providerdetails:
              label: Breadcrumb.Providers.Details
              route: usermanagement_showProviderContent
              defaults:
                id: 1
            editprovider:
              label: Breadcrumb.Edit.Provider
              route: usermanagement_editProvider

