imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: validator.mapping.cache.doctrine.apc
#    serializer:
#        cache: serializer.mapping.cache.apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            channels: ['!ginco']
            handler:      nested
        ginco:
            type: fingers_crossed
            action_level: error
            channels: 'ginco'
            handler: nested_ginco
        nested:
            type:  rotating_file
            path:  "%kernel.logs_dir%/symfony_%kernel.environment%.log"
            level: info
            max_files: 30
        nested_ginco:
            type:  rotating_file
            path:  "%kernel.logs_dir%/ginco_%kernel.environment%.log"
            level: info
            max_files: 30
        console:
            type:  console
