# Configuration file for help links
# Specific to DLB !!!
#
# For every help page, set attributes label an url (relative to help site domain).
# And routes of all pages with tis label/url.
#
# Example with one route:
#
# home:
#  label: Help
#  url: /index.html
#  route: homepage
#
# Example wih several routes:
#
# users:
#   label: Help on user management
#   url: /gestion-des-utilisateurs
#   routes:
#     - user_home
#     - user_edit
#     - user_add


home:
  label: Help.home
  url: /index.html
  route: homepage

usermanagement:
  label: Help.users
  url: /redirections/index.html
  routes:
    - usermanagement_home
    - usermanagement_showUsers
    - usermanagement_editUser
    - usermanagement_changePassword
    - usermanagement_showRoles
    - usermanagement_editRole
    - usermanagement_showProviders
    - usermanagement_showProviderContent
    - usermanagement_editProvider

datasets:
  label: Help.datasets
  url: /documentation/etapes_processus/etape_4.html#gerer-et-deposer-les-jeux-de-donnees
  routes:
    - all_jdd_list
    - user_jdd_list
    - jdd_show

import:
  label: Help.import
  url: /documentation/etapes_processus/etape_4.html#selectionner-et-importer-un-jeu-de-donnees-via-l-identifiant-tps
  routes:
    - jdd_new
    - integration_creation
    - integration_upload_data
    - integration_validate_upload

published_jdds:
  label: Help.published
  url: /faq/questions_techniques/donnees_jdd.html#quelles-sont-les-tele-procedures-ayant-fait-lobjet-dun-depot-legal
  routes:
    - published_jdds
    - published_jdds_by_tps

configurator:
  label: Help.configurator.home
  url: /redirections/index.html
  route: configurateur_homepage

configurator_models:
  label: Help.configurator.models
  url: /redirections/index.html
  routes:
    - configurateur_model_new
    - configurateur_model_index
    - configurateur_model_edit
    - configurateur_model_import
    - configurateur_model_view
    - configurateur_model_duplicate
    - configurateur_table_index
    - configurateur_table_fields
    - configurateur_table_edit
    - configurateur_table_view
    - configurateur_table_add_fields
    - configurateur_table_update_fields

configurator_import_models:
  label:  Help.configurator.import_models
  url: /redirections/index.html
  routes:
    - configurateur_dataset_import_index
    - configurateur_dataset_import_new
    - configurateur_dataset_import_edit
    - configurateur_dataset_import_view
    - configurateur_file_mappings
    - configurateur_field_mapping_new
    - configurateur_field_mapping_edit
    - configurateur_file_index
    - configurateur_file_edit
    - configurateur_file_fields
    - configurateur_file_view

configurator_data:
  label: Help.configurator.data
  url: /redirections/index.html
  routes:
    - configurateur_data_index
    - configurateur_data_new
    - configurateur_data_new_addtoformat
    - configurateur_data_show
    - configurateur_data_edit

platform_parameters:
  label: Help.platform_config
  url: /redirections/index.html
  routes:
    - configuration_parameters
    - configuration_homepage
    - configuration_presentation